# can use variables like {build} and {branch}
version: 1.0.{build}

image: Visual Studio 2017

environment:
  BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\\build"
  CTEST_OUTPUT_ON_FAILURE: 1

platform:
  - Win32

configuration:
  - Debug

before_build:
  - cd %BUILD_DIR%
  - cmake .. -DBUILD_TESTING=ON -DBUILD_LIB=ON -DCMAKE_CXX_FLAGS=/W1 -G"Visual Studio 15 2017"

after_build:
  - ctest --timeout 5 -C Debug -j4

build:
  parallel: true
  project: build/entt.sln
  verbosity: minimal
